POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "userName" : "levanha",
    "password" : "789"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{   
    "userName" : "letuanbao",
    "password" : "123456"
}

### 

POST  http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzIzYmI5MDIyNTBmMDRiYjg3N2JjN2QiLCJpYXQiOjE2NjMzNDMyMTB9.QSYLnbUbEAJe91eWYv8chmPd4b7Zjl0yk_HSmtE_LUs

{
    "title" : "HTML",
    "description" : "HTML 101",
    "url" : "youtube.com",
    "status" : "LEARNING"
}

