POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "userName" : "lequocdat",
    "password" : "456"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{   
    "userName" : "letuanbao",
    "password" : "123456"
}

###


POST http://localhost:5000/api/auth/login
Content-Type: application/json

{   
    "userName" : "levanha",
    "password" : "789"
}

### 

POST  http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzIzYmI5MDIyNTBmMDRiYjg3N2JjN2QiLCJpYXQiOjE2NjMzNDMyMTB9.QSYLnbUbEAJe91eWYv8chmPd4b7Zjl0yk_HSmtE_LUs

{
    "title" : "HTML",
    "description" : "HTML 101",
    "url" : "youtube.com",
    "status" : "LEARNING"
}

###

GET http://localhost:5000/api/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI0OTViYTk4Nzk3MWZiNjljNGMyNzciLCJpYXQiOjE2NjMzNDQ0NzZ9.yh43b_1McORueC2UfrDffadY8s-hT2lmJo28IE6Z8zQ

###

PUT  http://localhost:5000/api/posts/632499cf3745ac1fe19b0f80 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI0OTViYTk4Nzk3MWZiNjljNGMyNzciLCJpYXQiOjE2NjMzNDYzNDR9.2U1HEmE9unHsOFHxc2ods2UDuLWEOzf7xoxe1cJ0bmI

{
    "title" : "VueJs",
    "description" : "vue",
    "url" : "https://vue.org",
    "status" : "LEARNING"
}   